### ISSUE TITLE
ACTIVIDAD 7 JUICIO EXPERTO Y COSTOS JUDITH REYNA CRUZ SANTIAGO

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-jamm#4]
[PRACTICA 7_JUCIO EXPERTO Y COSTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-jamm/files/13191918/PRACTICA.7_JUCIO.EXPERTO.Y.COSTOS.pdf)

**Comment by NoeliaGlez** [comment]
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
